import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

import './globals.css'; // tvoj standardni css
import '../public/css/plugins/bootstrap.min.css';
import '../public/css/plugins/owl.carousel.min.css';
import '../public/css/plugins/owl.theme.default.min.css';
import '../public/css/plugins/flaticon.css';
import '../public/css/plugins/themify-icons.css';
import '../public/css/style.css';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>
        <link rel="stylesheet" href="/css/plugins.css" />
        <link rel="stylesheet" href="/css/style.css" />
      </head>
      <body className="bg-blck" suppressHydrationWarning={true}>
        <Navbar />
        {children}
        <Footer />

       
      </body>
    </html>
  );
}
